package Jetons;

public enum JetonScience {
URBANISME, ARTISANAT, JOAILLERIE, SCIENCE, PROPAGANDE, ARCHITECTURE, ECONOMIE, INGENIERIE, TACTIQUE, DECORATION, POLITIQUE, STRATEGIE, EDUCATION, CULTURE;
	public static void applique() {
	}}